name: CI test

on:
  workflow_dispatch:
    inputs:
      pesan:
        description: 'Isi pesanmu'
        required: true

jobs:
  test-runner:
    runs-on: ubuntu-latest 
    steps:
      - name: Hello world
        run: echo ${{ github.event.inputs.pesan }}
